// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package protoc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Enum int32

const (
	Enum_VAL_0 Enum = 0
	Enum_VAL_1 Enum = 17
	Enum_VAL_2 Enum = 364
)

var Enum_name = map[int32]string{
	0:   "VAL_0",
	17:  "VAL_1",
	364: "VAL_2",
}
var Enum_value = map[string]int32{
	"VAL_0": 0,
	"VAL_1": 17,
	"VAL_2": 364,
}

func (x Enum) String() string {
	return proto.EnumName(Enum_name, int32(x))
}
func (Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_example_ec08a9c60fc7dad6, []int{0}
}

type SimpleMessage struct {
	StringField          string   `protobuf:"bytes,1,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	Int32Field           int32    `protobuf:"varint,2,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field           int64    `protobuf:"varint,3,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	FloatField           float32  `protobuf:"fixed32,4,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	DoubleField          float64  `protobuf:"fixed64,5,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	BoolField            bool     `protobuf:"varint,6,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	EnumField            Enum     `protobuf:"varint,7,opt,name=enum_field,json=enumField,proto3,enum=protoc.Enum" json:"enum_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleMessage) Reset()         { *m = SimpleMessage{} }
func (m *SimpleMessage) String() string { return proto.CompactTextString(m) }
func (*SimpleMessage) ProtoMessage()    {}
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_ec08a9c60fc7dad6, []int{0}
}
func (m *SimpleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMessage.Unmarshal(m, b)
}
func (m *SimpleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMessage.Marshal(b, m, deterministic)
}
func (dst *SimpleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMessage.Merge(dst, src)
}
func (m *SimpleMessage) XXX_Size() int {
	return xxx_messageInfo_SimpleMessage.Size(m)
}
func (m *SimpleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMessage proto.InternalMessageInfo

func (m *SimpleMessage) GetStringField() string {
	if m != nil {
		return m.StringField
	}
	return ""
}

func (m *SimpleMessage) GetInt32Field() int32 {
	if m != nil {
		return m.Int32Field
	}
	return 0
}

func (m *SimpleMessage) GetInt64Field() int64 {
	if m != nil {
		return m.Int64Field
	}
	return 0
}

func (m *SimpleMessage) GetFloatField() float32 {
	if m != nil {
		return m.FloatField
	}
	return 0
}

func (m *SimpleMessage) GetDoubleField() float64 {
	if m != nil {
		return m.DoubleField
	}
	return 0
}

func (m *SimpleMessage) GetBoolField() bool {
	if m != nil {
		return m.BoolField
	}
	return false
}

func (m *SimpleMessage) GetEnumField() Enum {
	if m != nil {
		return m.EnumField
	}
	return Enum_VAL_0
}

type RepeatedFieldMessage struct {
	StringField          []string  `protobuf:"bytes,1,rep,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	Int32Field           []int32   `protobuf:"varint,2,rep,packed,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field           []int64   `protobuf:"varint,3,rep,packed,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	FloatField           []float32 `protobuf:"fixed32,4,rep,packed,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	DoubleField          []float64 `protobuf:"fixed64,5,rep,packed,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	BoolField            []bool    `protobuf:"varint,6,rep,packed,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	EnumField            []Enum    `protobuf:"varint,7,rep,packed,name=enum_field,json=enumField,proto3,enum=protoc.Enum" json:"enum_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RepeatedFieldMessage) Reset()         { *m = RepeatedFieldMessage{} }
func (m *RepeatedFieldMessage) String() string { return proto.CompactTextString(m) }
func (*RepeatedFieldMessage) ProtoMessage()    {}
func (*RepeatedFieldMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_ec08a9c60fc7dad6, []int{1}
}
func (m *RepeatedFieldMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedFieldMessage.Unmarshal(m, b)
}
func (m *RepeatedFieldMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedFieldMessage.Marshal(b, m, deterministic)
}
func (dst *RepeatedFieldMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedFieldMessage.Merge(dst, src)
}
func (m *RepeatedFieldMessage) XXX_Size() int {
	return xxx_messageInfo_RepeatedFieldMessage.Size(m)
}
func (m *RepeatedFieldMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedFieldMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedFieldMessage proto.InternalMessageInfo

func (m *RepeatedFieldMessage) GetStringField() []string {
	if m != nil {
		return m.StringField
	}
	return nil
}

func (m *RepeatedFieldMessage) GetInt32Field() []int32 {
	if m != nil {
		return m.Int32Field
	}
	return nil
}

func (m *RepeatedFieldMessage) GetInt64Field() []int64 {
	if m != nil {
		return m.Int64Field
	}
	return nil
}

func (m *RepeatedFieldMessage) GetFloatField() []float32 {
	if m != nil {
		return m.FloatField
	}
	return nil
}

func (m *RepeatedFieldMessage) GetDoubleField() []float64 {
	if m != nil {
		return m.DoubleField
	}
	return nil
}

func (m *RepeatedFieldMessage) GetBoolField() []bool {
	if m != nil {
		return m.BoolField
	}
	return nil
}

func (m *RepeatedFieldMessage) GetEnumField() []Enum {
	if m != nil {
		return m.EnumField
	}
	return nil
}

type MessageWithSubMessage struct {
	StringField          string         `protobuf:"bytes,1,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	SimpleMessage        *SimpleMessage `protobuf:"bytes,2,opt,name=simple_message,json=simpleMessage,proto3" json:"simple_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageWithSubMessage) Reset()         { *m = MessageWithSubMessage{} }
func (m *MessageWithSubMessage) String() string { return proto.CompactTextString(m) }
func (*MessageWithSubMessage) ProtoMessage()    {}
func (*MessageWithSubMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_ec08a9c60fc7dad6, []int{2}
}
func (m *MessageWithSubMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithSubMessage.Unmarshal(m, b)
}
func (m *MessageWithSubMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithSubMessage.Marshal(b, m, deterministic)
}
func (dst *MessageWithSubMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithSubMessage.Merge(dst, src)
}
func (m *MessageWithSubMessage) XXX_Size() int {
	return xxx_messageInfo_MessageWithSubMessage.Size(m)
}
func (m *MessageWithSubMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithSubMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithSubMessage proto.InternalMessageInfo

func (m *MessageWithSubMessage) GetStringField() string {
	if m != nil {
		return m.StringField
	}
	return ""
}

func (m *MessageWithSubMessage) GetSimpleMessage() *SimpleMessage {
	if m != nil {
		return m.SimpleMessage
	}
	return nil
}

type MessageWithRepeatedSubMessage struct {
	StringField          string           `protobuf:"bytes,1,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	SimpleMessage        []*SimpleMessage `protobuf:"bytes,2,rep,name=simple_message,json=simpleMessage,proto3" json:"simple_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MessageWithRepeatedSubMessage) Reset()         { *m = MessageWithRepeatedSubMessage{} }
func (m *MessageWithRepeatedSubMessage) String() string { return proto.CompactTextString(m) }
func (*MessageWithRepeatedSubMessage) ProtoMessage()    {}
func (*MessageWithRepeatedSubMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_ec08a9c60fc7dad6, []int{3}
}
func (m *MessageWithRepeatedSubMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithRepeatedSubMessage.Unmarshal(m, b)
}
func (m *MessageWithRepeatedSubMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithRepeatedSubMessage.Marshal(b, m, deterministic)
}
func (dst *MessageWithRepeatedSubMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithRepeatedSubMessage.Merge(dst, src)
}
func (m *MessageWithRepeatedSubMessage) XXX_Size() int {
	return xxx_messageInfo_MessageWithRepeatedSubMessage.Size(m)
}
func (m *MessageWithRepeatedSubMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithRepeatedSubMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithRepeatedSubMessage proto.InternalMessageInfo

func (m *MessageWithRepeatedSubMessage) GetStringField() string {
	if m != nil {
		return m.StringField
	}
	return ""
}

func (m *MessageWithRepeatedSubMessage) GetSimpleMessage() []*SimpleMessage {
	if m != nil {
		return m.SimpleMessage
	}
	return nil
}

type MessageWithOneof struct {
	StringField string `protobuf:"bytes,1,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	// Types that are valid to be assigned to OneofField:
	//	*MessageWithOneof_Int32OneofField
	//	*MessageWithOneof_Int64OneofField
	OneofField           isMessageWithOneof_OneofField `protobuf_oneof:"oneof_field"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MessageWithOneof) Reset()         { *m = MessageWithOneof{} }
func (m *MessageWithOneof) String() string { return proto.CompactTextString(m) }
func (*MessageWithOneof) ProtoMessage()    {}
func (*MessageWithOneof) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_ec08a9c60fc7dad6, []int{4}
}
func (m *MessageWithOneof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageWithOneof.Unmarshal(m, b)
}
func (m *MessageWithOneof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageWithOneof.Marshal(b, m, deterministic)
}
func (dst *MessageWithOneof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageWithOneof.Merge(dst, src)
}
func (m *MessageWithOneof) XXX_Size() int {
	return xxx_messageInfo_MessageWithOneof.Size(m)
}
func (m *MessageWithOneof) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageWithOneof.DiscardUnknown(m)
}

var xxx_messageInfo_MessageWithOneof proto.InternalMessageInfo

type isMessageWithOneof_OneofField interface {
	isMessageWithOneof_OneofField()
}

type MessageWithOneof_Int32OneofField struct {
	Int32OneofField int32 `protobuf:"varint,2,opt,name=int32_oneof_field,json=int32OneofField,proto3,oneof"`
}
type MessageWithOneof_Int64OneofField struct {
	Int64OneofField int64 `protobuf:"varint,3,opt,name=int64_oneof_field,json=int64OneofField,proto3,oneof"`
}

func (*MessageWithOneof_Int32OneofField) isMessageWithOneof_OneofField() {}
func (*MessageWithOneof_Int64OneofField) isMessageWithOneof_OneofField() {}

func (m *MessageWithOneof) GetOneofField() isMessageWithOneof_OneofField {
	if m != nil {
		return m.OneofField
	}
	return nil
}

func (m *MessageWithOneof) GetStringField() string {
	if m != nil {
		return m.StringField
	}
	return ""
}

func (m *MessageWithOneof) GetInt32OneofField() int32 {
	if x, ok := m.GetOneofField().(*MessageWithOneof_Int32OneofField); ok {
		return x.Int32OneofField
	}
	return 0
}

func (m *MessageWithOneof) GetInt64OneofField() int64 {
	if x, ok := m.GetOneofField().(*MessageWithOneof_Int64OneofField); ok {
		return x.Int64OneofField
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MessageWithOneof) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MessageWithOneof_OneofMarshaler, _MessageWithOneof_OneofUnmarshaler, _MessageWithOneof_OneofSizer, []interface{}{
		(*MessageWithOneof_Int32OneofField)(nil),
		(*MessageWithOneof_Int64OneofField)(nil),
	}
}

func _MessageWithOneof_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MessageWithOneof)
	// oneof_field
	switch x := m.OneofField.(type) {
	case *MessageWithOneof_Int32OneofField:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int32OneofField))
	case *MessageWithOneof_Int64OneofField:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int64OneofField))
	case nil:
	default:
		return fmt.Errorf("MessageWithOneof.OneofField has unexpected type %T", x)
	}
	return nil
}

func _MessageWithOneof_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MessageWithOneof)
	switch tag {
	case 2: // oneof_field.int32_oneof_field
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofField = &MessageWithOneof_Int32OneofField{int32(x)}
		return true, err
	case 3: // oneof_field.int64_oneof_field
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.OneofField = &MessageWithOneof_Int64OneofField{int64(x)}
		return true, err
	default:
		return false, nil
	}
}

func _MessageWithOneof_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MessageWithOneof)
	// oneof_field
	switch x := m.OneofField.(type) {
	case *MessageWithOneof_Int32OneofField:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Int32OneofField))
	case *MessageWithOneof_Int64OneofField:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Int64OneofField))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*SimpleMessage)(nil), "protoc.SimpleMessage")
	proto.RegisterType((*RepeatedFieldMessage)(nil), "protoc.RepeatedFieldMessage")
	proto.RegisterType((*MessageWithSubMessage)(nil), "protoc.MessageWithSubMessage")
	proto.RegisterType((*MessageWithRepeatedSubMessage)(nil), "protoc.MessageWithRepeatedSubMessage")
	proto.RegisterType((*MessageWithOneof)(nil), "protoc.MessageWithOneof")
	proto.RegisterEnum("protoc.Enum", Enum_name, Enum_value)
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_example_ec08a9c60fc7dad6) }

var fileDescriptor_example_ec08a9c60fc7dad6 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x41, 0x6f, 0xda, 0x30,
	0x14, 0xc7, 0x71, 0x0c, 0x6c, 0x79, 0x21, 0x2c, 0x44, 0x43, 0xda, 0x05, 0x2d, 0x70, 0xb2, 0xb6,
	0x09, 0x6d, 0x21, 0xca, 0x69, 0x97, 0x56, 0x6a, 0xd5, 0x43, 0xab, 0x4a, 0x46, 0x6a, 0x8f, 0x28,
	0x01, 0x43, 0x23, 0x25, 0x31, 0x22, 0x89, 0xc4, 0xb1, 0x87, 0xde, 0xfa, 0x25, 0xfa, 0x01, 0xfb,
	0x21, 0xaa, 0xd8, 0xa6, 0x0d, 0x87, 0x12, 0xaa, 0x9e, 0xe2, 0xfc, 0xdf, 0xcf, 0x7e, 0xcf, 0x7f,
	0xbf, 0x07, 0x26, 0xdb, 0x06, 0xc9, 0x3a, 0x66, 0xe3, 0xf5, 0x86, 0xe7, 0xdc, 0x6e, 0x8b, 0xcf,
	0x7c, 0xf4, 0xa0, 0x81, 0x39, 0x8d, 0xca, 0xc0, 0x15, 0xcb, 0xb2, 0x60, 0xc5, 0xec, 0x21, 0x74,
	0xb2, 0x7c, 0x13, 0xa5, 0xab, 0xd9, 0x32, 0x62, 0xf1, 0xe2, 0x07, 0x72, 0x10, 0xd1, 0xa9, 0x21,
	0xb5, 0xf3, 0x52, 0xb2, 0x7f, 0x82, 0x11, 0xa5, 0xf9, 0xc4, 0x55, 0x84, 0xe6, 0x20, 0xd2, 0xa2,
	0x20, 0xa4, 0x2a, 0xe0, 0x7b, 0x0a, 0xc0, 0x0e, 0x22, 0x58, 0x00, 0xbe, 0xf7, 0x0a, 0x2c, 0x63,
	0x1e, 0xe4, 0x0a, 0x68, 0x3a, 0x88, 0x68, 0x14, 0x84, 0x24, 0x81, 0x21, 0x74, 0x16, 0xbc, 0x08,
	0x63, 0xa6, 0x88, 0x96, 0x83, 0x08, 0xa2, 0x86, 0xd4, 0x24, 0x32, 0x00, 0x08, 0x39, 0x8f, 0x15,
	0xd0, 0x76, 0x10, 0xf9, 0x4a, 0xf5, 0x52, 0x91, 0xe1, 0xdf, 0x00, 0x2c, 0x2d, 0x12, 0x15, 0xfe,
	0xe2, 0x20, 0xd2, 0x75, 0x3b, 0xf2, 0xf6, 0xf3, 0xf1, 0x59, 0x5a, 0x24, 0x54, 0x2f, 0xe3, 0x02,
	0x1e, 0x3d, 0x6a, 0xf0, 0x9d, 0xb2, 0x35, 0x0b, 0x72, 0xb6, 0x10, 0xca, 0xfb, 0x6e, 0xe0, 0x5a,
	0x37, 0x70, 0x9d, 0x1b, 0xb8, 0xce, 0x0d, 0x5c, 0xeb, 0x06, 0xae, 0x73, 0x03, 0x1f, 0x76, 0x03,
	0x1f, 0x72, 0x63, 0x0b, 0x7d, 0x75, 0xff, 0xdb, 0x28, 0xbf, 0x9b, 0x16, 0xe1, 0x07, 0x7a, 0xe3,
	0x3f, 0x74, 0x33, 0xd1, 0x4f, 0xb3, 0x44, 0x6e, 0x12, 0xed, 0x61, 0xb8, 0xfd, 0x5d, 0xb2, 0xbd,
	0x6e, 0xa3, 0x66, 0x56, 0xfd, 0x1d, 0xdd, 0x23, 0x18, 0x54, 0x52, 0xef, 0x9e, 0xe4, 0xf3, 0x25,
	0xe0, 0xa3, 0x4b, 0x78, 0x42, 0x60, 0x55, 0x4a, 0xb8, 0x4e, 0x19, 0x5f, 0x1e, 0x93, 0xf5, 0x0f,
	0xf4, 0x64, 0x1b, 0xf0, 0x72, 0x47, 0x75, 0x34, 0x2e, 0x1a, 0xf4, 0x9b, 0x08, 0x89, 0xb3, 0xaa,
	0xb4, 0xef, 0xed, 0xd1, 0x62, 0x4e, 0x14, 0xed, 0x7b, 0x6f, 0xf4, 0xa9, 0x09, 0x46, 0x85, 0xfb,
	0x45, 0xa0, 0x59, 0x3e, 0x99, 0xad, 0x43, 0xeb, 0xe6, 0xe4, 0x72, 0xf6, 0xd7, 0x6a, 0xec, 0x96,
	0xff, 0xac, 0x9e, 0x0d, 0x72, 0xe9, 0x5a, 0xcf, 0x5a, 0x28, 0xc7, 0x7c, 0xf2, 0x12, 0x00, 0x00,
	0xff, 0xff, 0x80, 0x96, 0xe9, 0x2a, 0xfe, 0x03, 0x00, 0x00,
}
